- type: job
  id: Townsperson
  setPreference: true
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-townsperson
  description: job-description-townsperson
  playTimeTracker: Townsperson
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterOverallTimeRequirement
      min: 3600 # 1 hour
  startingGear: TownspersonGear
  icon: "JobIconTownPerson" # Corvax-Change
  supervisors: job-supervisors-townsfolk
  access:
  - TownsPerson # Corvax-Change
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - Townsfolk

- type: startingGear
  id: TownspersonGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitSettlerRags
    back: N14ClothingBackpackExplorer # Corvax-Change
    shoes: N14ClothingShoesBlack
    id: N14IDPassportTownsfolk
  innerClothingSkirt: N14ClothingUniformJumpskirtFalloutBlack
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledWastelander

- type: playTimeTracker
  id: Townsperson
