- type: job
  id: TownDeputy # Renamed to "Guard", don't touch the prototype ID
  setPreference: true
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-towndeputy
  description: job-description-towndeputy
  playTimeTracker: TownDeputy
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: Townsfolk
      min: 14400 # 4 hours
  startingGear: TownDeputyGear
  icon: "JobIconTownDeputy" # Forge-Change
  supervisors: job-supervisors-townsfolk
  access:
  - TownieLaw
  - TownieMechanic
  - TownsPerson # Forge-Change
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - Townsfolk

- type: startingGear
  id: TownDeputyGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTownGuard
    back: N14ClothingBackpackSatchelMilitary # Forge-Change
    shoes: N14ClothingBootsLeatherFilled
    id: N14IDBadgeTownDeputy
    belt: ClothingBeltRevolverfilled # Forge-Change
    pocket1: TownGuardKits
    pocket2: Handcuffs
  storage: # Forge-Change
    back:
    - N14BoxPlasticFilledWastelander
    - N14CombatKnife
    - MagazineBox10mm
    - MagazineBox44

- type: playTimeTracker
  id: TownDeputy
