- type: job
  id: BoSWestScribe
  setPreference: true
  name: job-name-bos-west-scribe
  description: job-description-bos-west-scribe
  playTimeTracker: BoSWestScribe
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodWest
      min: 54000 # 15 hours
  startingGear: BoSWestScribeGear
  alwaysUseSpawner: true
  icon: "JobIconBosMScriptor"
  supervisors: job-supervisors-bos-west
  access:
  - BoSWest
  - WestScribe
  - WestKnight
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodWest
      - type: CPRTraining

- type: startingGear
  id: BoSWestScribeGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSScribe
    back: N14ClothingBackpackSatchelMilitary
    shoes: N14ClothingBootsLeather
    # pocket1: NCRBoSMidwestScribekits
    id: N14IDBrotherhoodWestHolotag
    ears: N14ClothingHeadsetBOSWest
  storage:
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: BoSWestScribe
