- type: job
  id: CaravanLeader
  setPreference: true
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-caravan-leader
  description: job-description-caravan-leader
  playTimeTracker: CaravanLeader
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: CaravanCompany
      min: 7200 # 2 hours as Caravan member
  weight: 10
  startingGear: CaravanLeaderGear
  icon: "JobIconCaravanLeader" # Corvax-Change
  supervisors: job-supervisors-caravan-leader
  alwaysUseSpawner: true
  accessGroups:
  - CaravanCompany
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - CaravanCompany
      - type: CPRTraining

- type: startingGear
  id: CaravanLeaderGear
  equipment:
    head: N14ClothingHeadHatCaravanSuit
    jumpsuit: N14ClothingUniformJumpsuitCaravanSuit
    back: N14ClothingBackpackHiking # Corvax-Change
    shoes: N14ClothingShoesBlack
    pocket1: N14WeaponPistol12mm
    id: N14IDPassportCaravanLeader
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledWastelander
    - N14MagazinePistol12mm
    - N14MagazinePistol12mm

- type: playTimeTracker
  id: CaravanLeader
