- type: job
  id: NCRSoldier
  setPreference: true
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-ncr-soldier
  description: job-description-ncr-soldier
  playTimeTracker: NCRSoldier
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: NCR
      min: 10800 # 3 hours Corvax-Change
  startingGear: NCRSoldierGear
  icon: "JobIconNcrSoldier" # Corvax-Change
  supervisors: job-supervisors-ncr
  alwaysUseSpawner: true
  access:
  - NCR
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - NCR

- type: startingGear
  id: NCRSoldierGear
  equipment:
    head: N14ClothingHeadHatNCRHelmetMetalDesert # Corvax-Change
    back: N14ClothingBackpackNCR # Corvax-Change
    jumpsuit: N14ClothingUniformNCRDesert # Corvax-Change
    shoes: N14ClothingBootsLeatherFilled
    id: N14IDNCRDogtag
    pocket1: NCRtrooperloadoutkits
  innerClothingSkirt: N14ClothingUniformNCRDesert # Corvax-Change
  satchel: N14ClothingBackpackSatchelNCRFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledMilitaryNCR

- type: playTimeTracker
  id: NCRSoldier
