- type: job
  id: Wastelander
  setPreference: true
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-wastelander
  description: job-description-wastelander
  playTimeTracker: Wastelander
  startingGear: WastelanderGear
  icon: "JobIconWastelander" # Corvax-Change
  supervisors: job-supervisors-wastelander
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander

- type: startingGear
  id: WastelanderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitRags
    back: N14ClothingBackpackExplorer # Corvax-Change
    shoes: N14ClothingShoesRags
  innerClothingSkirt: N14ClothingUniformJumpskirtFalloutBlack
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledWastelander

- type: playTimeTracker
  id: Wastelander
