- type: job
  id: CaesarLegionDean
  setPreference: true
  name: job-name-caesar-legion-dean
  description: job-description-caesar-legion-dean
  playTimeTracker: CaesarLegionDean
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: CaesarLegion
    min: 72000 # 20 hours
  - !type:CharacterPlaytimeRequirement
      tracker: CaesarLegionLegionnaireVeteran
      min: 18000 # 5 hours
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterSexRequirement
    sex: Male
  - !type:CharacterGenderRequirement
    gender: Male
  startingGear: CaesarLegionDeanGear
  alwaysUseSpawner: true
  icon: "JobIconLegioner"
  supervisors: job-name-caesar-legion-supervisors
  canBeAntag: false
  access:
  - CaesarLegion
  - CaesarLegionDean
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - CaesarLegion
      - type: ReplacementAccent
        accent: latin
  - !type:AddTraitSpecial
    traits: [ LanguageLatin ]

- type: startingGear
  id: CaesarLegionDeanGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitLegionnaire
    neck: ClothingNeckRedScarf
    eyes: N14ClothingEyesGlassesWelding
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsBlack
    gloves: N14ClothingHandsGlovesTribal
    belt: N14Gladius
    pocket1: LegionDeanloadoutkits
    pocket2: N14WeaponPistol10mmPipe
    id: N14IDLegionaryMedalSilver3
  innerClothingSkirt: N14ClothingUniformJumpsuitLegionnaireOther
  storage:
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: CaesarLegionDean
