// Cherry-picked from space-station-14#32938 courtesy of Ilya246

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client.Stack;


[GenerateTypedNameReferences]
public sealed partial class StackCustomSplitWindow : DefaultWindow
{
    private const int Min = 1;
    private int _max = int.MaxValue;

    public StackCustomSplitWindow()
    {
        RobustXamlLoader.Load(this);
        AmountLineEdit.OnTextChanged += OnValueChanged;
    }

    public void SetMax(int max)
    {
        _max = max;
        MaximumAmount.Text = Loc.GetString("comp-stack-split-size", ("size", _max));
    }

    private void OnValueChanged(LineEdit.LineEditEventArgs args)
    {
        if (!int.TryParse(AmountLineEdit.Text, out var amount) ||
            amount > _max ||
            amount < Min)
            ApplyButton.Disabled = true;
        else
            ApplyButton.Disabled = false;
    }
}
